Basic power entry incorrectly states that a boiler consumes 1.8 MJ of fuel
deniszholob/factorio-cheat-sheet pull request #389
Opened 2024-04-03 09:42 UTC by samthegitguy

It should say "A steam boiler consumes 1.8MJ of fuel per second" or 1.8MW.

2024-04-03 18:23 UTC, deniszholob requested changes
I think the MJ per second is more appropriate since the boiler just ransfers the energy of fuel into water, wheas the steam engine does work on the energy yilding in power

so i would say change to
```
A [steam boiler](https://wiki.factorio.com/Boiler) can convert up to 60 units of water into steam per second, providing 1.8MJ of steam (at 165 °C) per second.

A steam boiler consumes 1.8MJ of fuel per second"
```
Also i love how github said build is successfull when its really not -_-
https://github.com/deniszholob/factorio-cheat-sheet/actions/runs/8536588905/job/23407747256?pr=389#step:8:64

2024-04-06 00:48 UTC, samthegitguy commented
Wiki says the boiler uses 1.8 MW of burner power, and "1.8 MJ per second" is the same thing as saying "1.8 MW."

However, I've made the changes. 

Do I need to do anything about the failed build?

2024-04-06 03:27 UTC, deniszholob approved these changes

2024-04-06 03:28 UTC, merged

2024-04-06 03:29 UTC, deniszholob commented
Its building ok now, just something was off in deployment, might be ok for master, if not ill take care of it.
Thanks!